import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import PrelineScript from "./PrelineScript";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Nukkad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        {children}</body>
        <PrelineScript/>
    </html>
  );
}
